### ISSUE TITLE
The kubeconfig in the S3 bucket is missing a name

### ISSUE THREAD

**Issue by sporkmonger** [coreos/terraform-aws-tectonic#15]
e.g.:

```
contexts:
- context:
    cluster: lab
    user: kubelet
```

Should probably be:

```
contexts:
- name: lab 
  context:
    cluster: lab
    user: kubelet
```

If you do a config merge without setting a `name`, `kubectl` will auto-insert a name value of `""`.
